---
- stat: path=/etc/cnva/storageclass-data.flag
  register: cnva_storageclass_data

- name: Create Storageclass manifest
  copy:
    dest: /opt/CNVA-DEV/storageclass-data.yaml
    content: |
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: data
      provisioner: kubernetes.io/cinder
      parameters:
        type: {{ lookup('env','OS_STORAGECLASS') }}
        availability: {{ lookup('env','OS_AZ') }}
  when: ansible_hostname == "{{ lookup('env','K8S_CLUSTER_NAME') |default('cnva') }}-{{ lookup('env','ADMIN_INSTANCE_SUFFIX') }}-1" and cnva_storageclass_data.stat.exists == False

- name: Create Storageclass 'data'
  shell: 'kubectl apply -f /opt/CNVA-DEV/storageclass-data.yaml'
  when: ansible_hostname == "{{ lookup('env','K8S_CLUSTER_NAME') |default('cnva') }}-{{ lookup('env','ADMIN_INSTANCE_SUFFIX') }}-1" and cnva_storageclass_data.stat.exists == False

- name: Create Storageclass flag
  file: 
    path: /etc/cnva/storageclass-data.flag
    state: touch
  when: ansible_hostname == "{{ lookup('env','K8S_CLUSTER_NAME') |default('cnva') }}-{{ lookup('env','ADMIN_INSTANCE_SUFFIX') }}-1" and cnva_storageclass_data.stat.exists == False

